import type { AdConnector, ChannelConfig, InsightRow } from './types';
import { cfg, jsonFetch } from './types';

// Google Ads — REST API v17. Auth: OAuth access_token (Bearer) + developer-token, and
// the customer id (no dashes). login-customer-id is set when acting under a manager (MCC).
// config: { access_token, developer_token, customer_id, login_customer_id? }.
// Pausing/budget = resource :mutate; stats = googleAds:searchStream with GAQL.
const BASE = 'https://googleads.googleapis.com/v17';

function ctx(config: ChannelConfig) {
  const token = cfg(config, 'access_token', 'GOOGLE_ADS_ACCESS_TOKEN');
  const dev = cfg(config, 'developer_token', 'GOOGLE_ADS_DEVELOPER_TOKEN');
  const customerId = (cfg(config, 'customer_id', 'GOOGLE_ADS_CUSTOMER_ID') || '').replace(/-/g, '');
  if (!token || !dev || !customerId) return null;
  const login = (cfg(config, 'login_customer_id', 'GOOGLE_ADS_LOGIN_CUSTOMER_ID') || '').replace(/-/g, '');
  const headers: Record<string, string> = {
    authorization: `Bearer ${token}`,
    'developer-token': dev,
    'content-type': 'application/json',
  };
  if (login) headers['login-customer-id'] = login;
  return { customerId, headers };
}

export const googleConnector: AdConnector = {
  platform: 'Google',

  async pauseAd(config, ref) {
    const c = ctx(config);
    // Google pauses at the ad-group-ad level: resource id is `{adGroupId}~{adId}`.
    if (!c || !ref.adGroupId || !ref.adId) return false;
    const resourceName = `customers/${c.customerId}/adGroupAds/${ref.adGroupId}~${ref.adId}`;
    const { ok } = await jsonFetch(`${BASE}/customers/${c.customerId}/adGroupAds:mutate`, {
      method: 'POST',
      headers: c.headers,
      body: JSON.stringify({ operations: [{ update: { resourceName, status: 'PAUSED' }, updateMask: 'status' }] }),
    });
    return ok;
  },

  async setBudget(config, ref, daily) {
    const c = ctx(config);
    // Budget lives on a campaignBudget resource (shared). ref.budgetId = its numeric id.
    if (!c || !ref.budgetId) return false;
    const resourceName = `customers/${c.customerId}/campaignBudgets/${ref.budgetId}`;
    const amountMicros = Math.round(daily * 1_000_000);
    const { ok } = await jsonFetch(`${BASE}/customers/${c.customerId}/campaignBudgets:mutate`, {
      method: 'POST',
      headers: c.headers,
      body: JSON.stringify({ operations: [{ update: { resourceName, amountMicros }, updateMask: 'amount_micros' }] }),
    });
    return ok;
  },

  async uploadCreative(config, cr) {
    // Responsive Search Ads are already generated by campaign-agent; creating a live ad
    // needs an ad group + full RSA asset payload. Not auto-built here (client owns
    // connectivity + the pool). campaign-agent.ts produces the RSA content itself.
    void cr;
    return { ok: false, error: 'google_upload_not_implemented' };
  },

  async fetchInsights(config, ref) {
    const c = ctx(config);
    if (!c || !ref.adId) return null;
    const query =
      'SELECT metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions, ' +
      'metrics.conversions_value FROM ad_group_ad ' +
      `WHERE ad_group_ad.ad.id = ${ref.adId} DURING LAST_30_DAYS`;
    const { ok, json } = await jsonFetch(`${BASE}/customers/${c.customerId}/googleAds:searchStream`, {
      method: 'POST',
      headers: c.headers,
      body: JSON.stringify({ query }),
    });
    if (!ok) return null;
    // searchStream returns an array of { results: [...] } chunks.
    const chunks = Array.isArray(json) ? (json as { results?: unknown[] }[]) : [json as { results?: unknown[] }];
    let impressions = 0, clicks = 0, costMicros = 0, conversions = 0, revenue = 0;
    for (const chunk of chunks) {
      for (const r of (chunk.results ?? []) as { metrics?: Record<string, string | number> }[]) {
        const m = r.metrics ?? {};
        impressions += Number(m.impressions ?? 0) || 0;
        clicks += Number(m.clicks ?? 0) || 0;
        costMicros += Number(m.costMicros ?? m.cost_micros ?? 0) || 0;
        conversions += Number(m.conversions ?? 0) || 0;
        revenue += Number(m.conversionsValue ?? m.conversions_value ?? 0) || 0;
      }
    }
    if (impressions === 0 && clicks === 0) return null;
    return { impressions, clicks, spend: costMicros / 1_000_000, conversions, revenue };
  },

  async createCampaign(config, spec) {
    const c = ctx(config);
    if (!c) return { ok: false, error: 'google_not_configured' };
    // 1) Shared campaign budget (daily, micros). 2) Search campaign (PAUSED) on it.
    // Ad groups + Responsive Search Ads are generated by campaign-agent and added
    // separately (they need keywords/assets the client scopes), so we return a note.
    const amountMicros = Math.round(spec.dailyBudget * 1_000_000);
    const budgetRes = await jsonFetch(`${BASE}/customers/${c.customerId}/campaignBudgets:mutate`, {
      method: 'POST',
      headers: c.headers,
      body: JSON.stringify({ operations: [{ create: { name: `${spec.name} budget`, amountMicros, deliveryMethod: 'STANDARD', explicitlyShared: false } }] }),
    });
    if (!budgetRes.ok) return { ok: false, error: 'google_budget_failed' };
    const budgetResource = ((budgetRes.json.results as { resourceName?: string }[] | undefined)?.[0]?.resourceName) || '';
    if (!budgetResource) return { ok: false, error: 'google_budget_no_resource' };

    const campRes = await jsonFetch(`${BASE}/customers/${c.customerId}/campaigns:mutate`, {
      method: 'POST',
      headers: c.headers,
      body: JSON.stringify({
        operations: [{
          create: {
            name: spec.name,
            status: 'PAUSED',
            advertisingChannelType: 'SEARCH',
            campaignBudget: budgetResource,
            manualCpc: {},
            networkSettings: { targetGoogleSearch: true, targetSearchNetwork: true, targetContentNetwork: false },
          },
        }],
      }),
    });
    if (!campRes.ok) return { ok: false, error: 'google_campaign_failed' };
    const campaignResource = ((campRes.json.results as { resourceName?: string }[] | undefined)?.[0]?.resourceName) || undefined;
    const budgetId = budgetResource.split('/').pop();
    return { ok: true, campaignId: campaignResource, note: `google: campaign+budget created (paused, budgetId ${budgetId}). Ad groups + RSAs pending.` };
  },
};
